### PR TITLE
Added setters and getters.

### PR DESCRIPTION
**Pull request by delitestudio**
Hello, we have added setters and getters for your class.
We have also fixed some Android Studio warnings.

### CODE REVIEW

**Comment by pkleczko** [comment]
Hi, 

Thanks for this pull, I thought about it but recently had very limited time so nice that you have already done it.

**Comment by delitestudio** [comment]
You are welcome. The code "as is" does not refresh the internal states of the component, so some of them does not change the view, can you please fix this? It's not so clear how some of them are supposed to work.

Than after it's resolved can you release a new version on jcenter so this upgrade will be available to everyone directly from Android Studio? Thanks! I think you can close two tickets about this.

**Comment by pkleczko** [comment]
For now I just uploaded it to jcenter with your setters/getters for view init. Hope to have enough time to check it and make it work as live changes (updating view). It's not so obvious. Anyway, very thanks to you for this.

**Comment by delitestudio** [comment]
Hello, we have fixed (and tested) some of them in another pull request.
If we have time we can fix the remaining setter.

**Pull request merged**
